// Bu dosya, Göç İdaresi tarafından ikamet iznine kapatılan mahallelerin listesini içerir.
// Veri yapısı: İl -> İlçe -> [Mahalle Listesi]

export const RESTRICTED_LOCATIONS: Record<string, Record<string, string[]>> = {
  "Adana": {
    "Ceyhan": ["BOTA MAHALLESİ"],
    "Çukurova": ["MEMİŞLİ MAHALLESİ", "FADIL MAHALLESİ", "BOZCALAR MAHALLESİ", "ÖRCÜN MAHALLESİ", "KÜÇÜKÇINAR MAHALLESİ"],
    "Karataş": ["TABAKLAR MAHALLESİ", "ÇAVUŞLU MAHALLESİ", "KARAGÖÇER MAHALLESİ", "ATAKÖY MAHALLESİ", "BEBELİ MAHALLESİ", "KAPI MAHALLESİ", "YENİ MAHALLESİ", "BAHÇE MAHALLESİ"],
    "Kozan": ["AKARCA MAHALLESİ"],
    "Sarıçam": ["İSTİKLAL MAHALLESİ", "BALCALI MAHALLESİ"],
    "Seyhan": [
      "ÇAPUTÇU MAHALLESİ", "YEŞİLYUVA MAHALLESİ", "BEŞOCAK MAHALLESİ", "KOCAVEZİR MAHALLESİ", "TEPEBAĞ MAHALLESİ",
      "MİRZAÇELEBİ MAHALLESİ", "KURUKÖPRÜ MAHALLESİ", "ULUCAMİİ MAHALLESİ", "ALİDEDE MAHALLESİ", "KARASOKU MAHALLESİ",
      "GÜLPINAR MAHALLESİ", "HANEDAN MAHALLESİ", "MESTANZADE MAHALLESİ", "HÜRRİYET MAHALLESİ", "SARIYAKUP MAHALLESİ",
      "MEYDAN MAHALLESİ", "ŞEHİTDURAN MAHALLESİ", "KAYALIBAĞ MAHALLESİ", "DUMLUPINAR MAHALLESİ", "TÜRKOCAĞI MAHALLESİ",
      "SUCUZADE MAHALLESİ", "YENİBEY MAHALLESİ", "DÖRTAĞAÇ MAHALLESİ", "KAYIŞLI MAHALLESİ", "HURMALI MAHALLESİ",
      "İSTİKLAL MAHALLESİ", "ONUR MAHALLESİ", "DENİZLİ MAHALLESİ"
    ],
    "Yumurtalık": ["HAMZALI MAHALLESİ", "KIRMIZIDAM MAHALLESİ", "KUZUPINARI MAHALLESİ"],
    "Yüreğir": [
      "YEŞİL BAĞLAR MAHALLESİ", "DOĞANKENT CUMHURİYET MAHALLESİ", "BAHÇELİEVLER MAHALLESİ", "GAZİPAŞA MAHALLESİ",
      "DÜZCE MAHALLESİ", "SOLAKLI CUMHURİYET MAHALLESİ", "BAŞAK MAHALLESİ", "YUNUS EMRE MAHALLESİ", "KÖPRÜGÖZÜ MAHALLESİ",
      "DEDE KORKUT MAHALLESİ", "YUNUSOĞLU HÜRRİYET MAHALLESİ", "PEKMEZLİ MAHALLESİ", "AYDINCIK MAHALLESİ", "GÖKÇELİ MAHALLESİ",
      "KADIKÖY MAHALLESİ", "YERDELEN MAHALLESİ", "YALNIZCA MAHALLESİ", "ÇAĞIRKANLI MAHALLESİ", "SAZAK MAHALLESİ",
      "KİREMİTHANE MAHALLESİ", "19 MAYIS MAHALLESİ", "SİNANPAŞA MAHALLESİ", "KOZA MAHALLESİ", "ANADOLU MAHALLESİ",
      "SARIÇAM MAHALLESİ", "DOĞANKENT KIŞLA MAHALLESİ", "CUMHURİYET MAHALLESİ"
    ]
  },
  "Adıyaman": {
    "Adıyaman Merkez": [
      "AKPINAR KÖYÜ, MALOĞLU MEZRASI", "AKDERE KÖYÜ, AKINCILAR (ÇERÇİYAN) MEZRASI", "ULUCAMİ MAHALLESİ", "KAPCAMİ MAHALLESİ",
      "GÖZEBAŞI KÖYÜ, MADUN MEZRASI", "KAYALI KÖYÜ", "MARA MAHALLESİ", "MUSALLA MAHALLESİ", "BEBEK KÖYÜ, MAZLIK MEZRASI",
      "LOKMAN KÖYÜ", "SIRATUT MAHALLESİ", "ESKİHÜSNÜMANSUR KÖYÜ"
    ],
    "Besni": ["DUMLUPINAR MAHALLESİ", "CİRİT MEYDANI MAHALLESİ", "YENİ BESNİ MAHALLESİ"],
    "Çelikhan": ["AKSU KÖYÜ, DEVEBOYNU MEZRASI"],
    "Kahta": ["TURANLI KÖYÜ, BÜYÜTME MEVKİİ", "ÇAYBAŞI KÖYÜ, DUMANLI MEZRASI"],
    "Samsat": ["UZUNTEPE KÖYÜ, AĞAKÖY MEZRASI"]
  },
  "Afyonkarahisar": {
    "Afyonkarahisar Merkez": [
      "CUMHURİYET MAHALLESİ", "AFYONKARAHİSAR OSB MAHALLESİ", "ERENLER MAHALLESİ", "ZAFER MAHALLESİ", "YUNUS EMRE MAHALLESİ",
      "MECİDİYE MAHALLESİ", "MARULCU MAHALLESİ", "DAİRECEP MAHALLESİ", "FAKIPAŞA MAHALLESİ", "BURHANİYE KÖYÜ", "SAADET KÖYÜ",
      "YARENLER MAHALLESİ", "SÜMER MAHALLESİ"
    ],
    "Dinar": ["YÜKSEL KÖYÜ, SAĞBAŞLI MEVKİİ", "CAMİKEBİR MAHALLESİ", "YÜKSEL KÖYÜ, AKKANATLI MEVKİİ", "ÇAKICI KÖYÜ", "TOPTEPE MAHALLESİ", "ÜÇLERCE MAHALLESİ"],
    "Emirdağ": ["TEPEKÖY KÖYÜ"]
  },
  "Ağrı": {
    "Patnos": ["YÜNCÜLER KÖYÜ"]
  },
  "Aksaray": {
    "Aksaray Merkez": [
      "ZİNCİRLİ MAHALLESİ", "MİNARECİK MAHALLESİ", "DERE MAHALLESİ", "HAMİDİYE MAHALLESİ", "SOFULAR MAHALLESİ",
      "HACIHASANLI MAHALLESİ", "MUHSİN ÇELEBİ MAHALLESİ", "TAŞPINAR BELDESİ, ERENLER OSB MAHALLESİ"
    ],
    "Eskil": ["BAŞARAN KÖYÜ, BUTACI YAYLASI YAYLA EVLERİ", "GÜNEŞLİ KÖYÜ, KARABURUN YAYLASI YAYLA EVLERİ"],
    "Ortaköy / Aksaray": ["OĞUZLAR KÖYÜ, OĞUZLAR 2 MEVKİİ"]
  },
  "Amasya": {
    "Amasya Merkez": ["YÜZEVLER MAHALLESİ"]
  },
  "Ankara": {
    "Altındağ": ["TÜM MAHALLELER"], // Not: CSV'de "TÜM MAHALLELER" olarak belirtilmiş
    "Beypazarı": ["BEYTEPE MAHALLESİ", "RÜSTEMPAŞA MAHALLESİ", "ZAFER MAHALLESİ", "İSTİKLAL MAHALLESİ", "CUMHURİYET MAHALLESİ"],
    "Çankaya": ["DEVLET MAHALLESİ", "CUMHURİYET MAHALLESİ"],
    "Keçiören": ["YEŞİLÖZ MAHALLESİ"],
    "Mamak": ["TÜM MAHALLELER"], // Not: CSV'de "TÜM MAHALLELER"
    "Polatlı": ["ESENTEPE MAHALLESİ", "GÜLVEREN MAHALLESİ", "YENİ MAHALLESİ"],
    "Sincan": ["MALIKÖY BAŞKENT OSB MAHALLESİ"],
    "Yenimahalle": ["ANADOLU MAHALLESİ", "İVEDİKKÖY MAHALLESİ", "KARŞIYAKA MAHALLESİ"]
  },
  "Antalya": {
    "Alanya": ["KARGICAK MAHALLESİ", "MAHMUTLAR MAHALLESİ", "KESTEL MAHALLESİ", "AVSALLAR MAHALLESİ"],
    "Döşemealtı": ["AOSB2KISIM MAHALLESİ", "AOSB3KISIM MAHALLESİ"],
    "Konyaaltı": ["LİMAN MAHALLESİ", "HURMA MAHALLESİ", "SARISU MAHALLESİ"],
    "Muratpaşa": ["TOPÇULAR MAHALLESİ"]
  },
  "Bartın": {
    "Bartın Merkez": ["ORTA MAHALLESİ", "KARASU KÖYÜ, İNKUM İSKELE MEVKİİ", "GÜZELCEHİSAR KÖYÜ, İNKUM YENİ MAHALLESİ"]
  },
  "Batman": {
    "Beşiri": ["UĞURCA KÖYÜ", "ÜÇKUYULAR KÖYÜ"]
  },
  "Bayburt": {
    "Bayburt Merkez": ["YOLALTI KÖYÜ, YOLALTI OSB MEVKİİ"]
  },
  "Bilecik": {
    "Bilecik Merkez": ["BAŞKÖY KÖYÜ, MÜCAVİR DIŞI MEVKİİ", "HÜRRİYET 2.OSB MAHALLESİ", "İSTİKLAL MAHALLESİ"],
    "Söğüt": ["ÇALTI KÖYÜ, ŞEN MEVKİİ"]
  },
  "Bingöl": {
    "Genç": ["YENİYAZI KÖYÜ, FIRAT MEZRASI"]
  },
  "Bolu": {
    "Bolu Merkez": ["FASIL KÖYÜ, URAN MEVKİİ", "PELİTCİK KÖYÜ, ŞABANLAR MEVKİİ", "BÜYÜKCAMİ MAHALLESİ"],
    "Dörtdivan": ["DOĞANCILAR KÖYÜ, GEREDE YOLU MEVKİİ"],
    "Gerede": ["YAKAKAYA KÖYÜ, YUNUSLAR MEVKİİ", "ORTA MAHALLESİ", "BAHÇEDERE KÖYÜ, MERKEZ MEVKİİ"],
    "Mengen": ["KUZGÖL KÖYÜ, YILDIZ MEVKİİ", "TEBERİKLER KÖYÜ, YONSAKLAR MEVKİİ"],
    "Mudurnu": ["SÜRMELİ KÖYÜ, ÇAYIRALTI MEVKİİ"]
  },
  "Burdur": {
    "Bucak": ["ÇAMLICAOSB MAHALLESİ"],
    "Burdur Merkez": ["KUYU MAHALLESİ", "KARASENİR MAHALLESİ", "DEĞİRMENLER MAHALLESİ", "İNÖNÜ MAHALLESİ", "KONAK MAHALLESİ", "PAZAR MAHALLESİ", "ÇEŞMEDAMI MAHALLESİ"],
    "Çeltikçi": ["ÇEBİŞ KÖYÜ, ORTAYOL MEVKİİ"],
    "Gölhisar": ["SORKUN KÖYÜ"]
  },
  "Bursa": {
    "Karacabey": ["FEVZİPAŞA MAHALLESİ"],
    "Nilüfer": ["FETHİYEOSB MAHALLESİ"],
    "Osmangazi": [
      "DEMİRTAŞ DUMLUPINAROSB MAHALLESİ", "SELİMİYE MAHALLESİ", "HOCAHASAN MAHALLESİ", "ÇIRPAN MAHALLESİ",
      "İNTİZAM MAHALLESİ", "ALTIPARMAK MAHALLESİ", "ALACAMESCİT MAHALLESİ", "AHMETPAŞA MAHALLESİ",
      "KİREMİTÇİ MAHALLESİ", "SANTRAL GARAJ MAHALLESİ", "DOĞANBEY MAHALLESİ", "ŞEHABETTİNPAŞA MAHALLESİ",
      "KURUÇEŞME MAHALLESİ"
    ],
    "Yenişehir / Bursa": ["HIDIRBALİ MAHALLESİ"],
    "Yıldırım": ["ANADOLU MAHALLESİ", "DUAÇINARI MAHALLESİ", "BEYAZIT MAHALLESİ"]
  },
  "Çanakkale": {
    "Ayvacık / Çanakkale": ["ADATEPE KÖYÜ, PINARALTI MEVKİİ", "PAŞAKÖY KÖYÜ, PAŞAKÖY ALTI MEVKİİ"],
    "Bayramiç": ["BEKİRLER KÖYÜ"],
    "Biga": ["AĞAKÖY KÖYÜ, AĞAKÖY (MÜCAVİR) MEVKİİ"],
    "Çanakkale Merkez": ["IŞIKLAR KÖYÜ, TESTİCİKIRI MEVKİİ", "KEMALPAŞA MAHALLESİ"],
    "Gelibolu": ["KAVAKKÖY BELDESİ, CUMHURİYET MAHALLESİ", "BURHANLI KÖYÜ, DOĞA MEVKİİ", "ADİLHAN KÖYÜ, BOSTANLIK MEVKİİ"],
    "Gökçeada": ["ŞİRİNKÖY KÖYÜ"]
  },
  "Çankırı": {
    "Çankırı Merkez": ["İNCİLİ ÇEŞME MAHALLESİ", "AYAN KÖYÜ, MERKEZ MEVKİİ", "TABAKHANE MAHALLESİ"],
    "Çerkeş": ["ÖRENKÖY KÖYÜ, DERE YAYLA YAYLA EVLERİ", "YEŞİLÖZ KÖYÜ, YEŞİLOVA MEVKİİ"],
    "Ilgaz": ["ÖDEMİŞ KÖYÜ, SARAY MEVKİİ"],
    "Korgun": ["BÜYÜKOSB MAHALLESİ"],
    "Kurşunlu": ["SARIALAN KÖYÜ, PINARCIK MEVKİİ"],
    "Şabanözü": ["MARTKÖY KÖYÜ, ÇADIR MEVKİİ"]
  },
  "Çorum": {
    "Çorum Merkez": [
      "KADIKIRI KÖYÜ, KADIKIRI MÜCAVİR MEVKİİ", "SARIMBEY KÖYÜ, SARIMBEY MÜCAVİR MEVKİİ",
      "KARAPINAR KÖYÜ, KARAPINAR MÜCAVİR MEVKİİ", "ESKİEKİN KÖYÜ, HARMANTARLA MEVKİİ",
      "ÇOMARBAŞI KÖYÜ, RIÇVANLAR MEVKİİ", "HAMDİKÖY KÖYÜ, AŞAĞI MEVKİİ", "ÇEPNİ MAHALLESİ"
    ]
  },
  "Denizli": {
    "Merkezefendi": ["ZAFER MAHALLESİ"]
  },
  "Diyarbakır": {
    "Bismil": ["KARACIK MAHALLESİ", "KARAPINAR MAHALLESİ"],
    "Silvan": ["ÇOBANTEPE MAHALLESİ"]
  },
  "Düzce": {
    "Düzce Merkez": ["ORHANGAZİ MAHALLESİ", "BURHANİYE MAHALLESİ"]
  },
  "Elazığ": {
    "Baskil": ["KARAKAŞ KÖYÜ, YUKARI ATLILAR MEZRASI"],
    "Elazığ Merkez": [
      "ÖKSÜZUŞAĞI KÖYÜ, ALİ ÇAVUŞ MEZRASI", "SANAYİ MAHALLESİ", "ÇARŞI MAHALLESİ", "SÜTLÜCE KÖYÜ",
      "SÜTLÜCE KÖYÜ, SÜTLÜCE MEVKİİ", "ALACA KÖYÜ, ALACA(MERKEZ) MEVKİİ", "BALLICA KÖYÜ, BALLICA MEVKİİ"
    ],
    "Keban": ["BADEMLİ KÖYÜ, SİNO MEZRASI MEZRASI", "ALTIYAKA KÖYÜ, DEDE MEZRASI"],
    "Sivrice": ["BEKÇİTEPE KÖYÜ, DOĞANLAR MEZRASI"]
  },
  "Erzincan": {
    "Erzincan Merkez": ["KARAAĞAÇ MAHALLESİ"],
    "İliç": ["AĞILDERE KÖYÜ, APUŞTA MEZRASI"],
    "Kemah": ["GÖLKAYNAK KÖYÜ, GİNDİRA MEVKİİ"],
    "Tercan": ["KONARLI KÖYÜ", "ÇALKIŞLA KÖYÜ"]
  },
  "Eskişehir": {
    "Odunpazarı": ["75. YIL OSB MAHALLESİ", "HUZUR MAHALLESİ"],
    "Tepebaşı": ["MUTTALİP ORTA MAHALLESİ"]
  },
  "Gaziantep": {
    "Araban": ["DUMLUPINAR MAHALLESİ", "MEHMET GÖKÇEK MAHALLESİ"],
    "İslahiye": [
      "ÖRTÜLÜ MAHALLESİ", "HÜRRİYET MAHALLESİ", "CEVDETPAŞA MAHALLESİ", "FEVZİ ÇAKMAK MAHALLESİ", "PINARBAŞI MAHALLESİ",
      "DEĞİRMENCİK MAHALLESİ", "ERENLER MAHALLESİ", "AYDINLIK MAHALLESİ", "BEYLER MAHALLESİ", "DERVİŞPAŞA MAHALLESİ",
      "ATATÜRK MAHALLESİ", "KIRIKÇALI MAHALLESİ", "YENİ MAHALLESİ", "HACİ ALİ ÖZTÜRK MAHALLESİ"
    ],
    "Karkamış": [
      "GÜRÇAY MAHALLESİ", "BEŞKILIÇ MAHALLESİ", "LOJMANLAR MAHALLESİ", "KEPİRLER MAHALLESİ", "BALABAN MAHALLESİ",
      "ERENYOLU MAHALLESİ", "AKÇAKÖY MAHALLESİ", "YARIMCA MAHALLESİ"
    ],
    "Nizip": [
      "BELKIS (MERKEZ) MAHALLESİ", "CUMHURİYET MAHALLESİ", "ŞIHLAR MAHALLESİ", "SAHA MAHALLESİ", "TAHTANİ MAHALLESİ",
      "ŞAHİNBEY MAHALLESİ", "İSTASYON MAHALLESİ", "FEVZİ PAŞA MAHALLESİ", "HAFIZPAŞA MAHALLESİ", "PAZAR CAMİİ MAHALLESİ",
      "ZEYTİNLİK MAHALLESİ", "FEVKANİ MAHALLESİ", "İSTİKLAL MAHALLESİ", "NAMIK KEMAL MAHALLESİ", "BELKIS MAHALLESİ",
      "TURNALI MAHALLESİ", "ATATÜRK MAHALLESİ", "KIBRIS MAHALLESİ", "NAHIRTEPE MAHALLESİ", "YEŞİLEVLER MAHALLESİ",
      "MİMAR SİNAN MAHALLESİ"
    ],
    "Nurdağı": ["ASLANLI MAHALLESİ", "GEDİKLİ MAHALLESİ", "ESENYURT MAHALLESİ"],
    "Oğuzeli": [
      "TAŞÇANAK MAHALLESİ", "ÇAVUŞBAŞI MAHALLESİ", "BULDUK MAHALLESİ", "KURTULUŞ MAHALLESİ", "DEVEHÜYÜĞÜ MAHALLESİ",
      "GÜLLÜK MAHALLESİ", "BEŞDELİ MAHALLESİ", "AŞAĞI GÜNEYSE MAHALLESİ", "OĞUZLAR MAHALLESİ", "ŞIH KÜÇÜKKARACAVİRAN MAHALLESİ",
      "SUBAŞI MAHALLESİ"
    ],
    "Şahinbey": [
      "KARATARLA MAHALLESİ", "EYÜPOĞLU MAHALLESİ", "ALAYBEY MAHALLESİ", "SAVCILI MAHALLESİ", "AYDINBABA MAHALLESİ",
      "BEY MAHALLESİ", "KOZANLI MAHALLESİ", "KARAGÖZ MAHALLESİ", "TIŞLAKİ MAHALLESİ", "SUYABATMAZ MAHALLESİ",
      "KILINÇOĞLU MAHALLESİ", "ŞEKEROĞLU MAHALLESİ", "SULTAN SELİM MAHALLESİ", "BOSTANCI MAHALLESİ", "ŞAHVELİ MAHALLESİ",
      "SEFERPAŞA MAHALLESİ", "ETİLER MAHALLESİ", "AKYOL MAHALLESİ", "CABİ MAHALLESİ", "SAKARYA MAHALLESİ",
      "CEMAL GÜRSEL MAHALLESİ", "ÜNALDI MAHALLESİ", "SAÇAKLI MAHALLESİ", "TÜRKTEPE MAHALLESİ", "KOZLUCA MAHALLESİ",
      "ŞENYURT MAHALLESİ", "HOŞGÖR MAHALLESİ", "KANALICI MAHALLESİ", "TEKSTİLKENT MAHALLESİ", "YAVUZLAR MAHALLESİ",
      "KEPENEK MAHALLESİ", "İNÖNÜ MAHALLESİ", "BEKİRBEY MAHALLESİ", "ALİBABA MAHALLESİ", "BOZOKLAR MAHALLESİ",
      "YUKARIBAYIR MAHALLESİ", "BOYACI MAHALLESİ", "TURAN EMEKSİZ MAHALLESİ", "BARIŞ MAHALLESİ", "ÜÇOKLAR MAHALLESİ",
      "KARAYILAN MAHALLESİ", "DUMLUPINAR MAHALLESİ", "KIBRIS MAHALLESİ", "GÜMÜŞTEKİN MAHALLESİ", "ALLEBEN MAHALLESİ",
      "YAZICIK MAHALLESİ", "DÜZTEPE MAHALLESİ", "KAHVELİPINAR MAHALLESİ", "CUMHURİYET MAHALLESİ", "ESENTEPE MAHALLESİ",
      "NURİPAZARBAŞI MAHALLESİ", "BEYDİLLİ MAHALLESİ", "ÇAMLICA MAHALLESİ", "TÜRKMENLER MAHALLESİ", "KURBANBABA MAHALLESİ",
      "TÖRELİ MAHALLESİ", "AKDERE MAHALLESİ", "CENGİZ TOPEL MAHALLESİ", "KONAK MAHALLESİ", "GÜZELVADİ MAHALLESİ",
      "PERİLİKAYA MAHALLESİ", "YEŞİLPINAR MAHALLESİ", "25 ARALIK MAHALLESİ", "VATAN MAHALLESİ", "YEŞİLKENT MAHALLESİ",
      "BEYBAHÇE MAHALLESİ", "BEYAZLAR MAHALLESİ", "YAMAÇTEPE MAHALLESİ", "BURÇ KARAKUYU MAHALLESİ", "ULAŞ MAHALLESİ",
      "KAVAKLIK MAHALLESİ", "KÜÇÜKKIZILHİSAR MAHALLESİ", "ONUR MAHALLESİ", "İSTİKLAL MAHALLESİ", "MALAZGİRT MAHALLESİ",
      "DENİZ MAHALLESİ", "BİNEVLER MAHALLESİ", "BAHÇELİEVLER MAHALLESİ"
    ],
    "Şehitkamil": [
      "AKTOPRAK SB MAHALLESİ", "BAŞPINAR(ORGANİZE)OSB MAHALLESİ", "NESİMİ MAHALLESİ", "YAPRAK MAHALLESİ", "ÇAKMAK MAHALLESİ",
      "İNCİLİKAYA MAHALLESİ", "ÇAĞLAYAN MAHALLESİ", "EYDİBABA MAHALLESİ", "HUMANIZ MAHALLESİ", "GÖZTEPE MAHALLESİ",
      "SACIR MAHALLESİ", "DÜLÜKBABA MAHALLESİ", "ÇIKSORUT MAHALLESİ", "KARAOĞLAN MAHALLESİ", "KARŞIYAKA MAHALLESİ",
      "HÜRRİYET MAHALLESİ", "MİTHATPAŞA MAHALLESİ", "SİNAN OSB MAHALLESİ", "HASIRCIOĞLU MAHALLESİ", "TAŞLICA MAHALLESİ",
      "MÜNÜFPAŞA MAHALLESİ", "YUNUS EMRE MAHALLESİ", "SAM MAHALLESİ", "GİRNE MAHALLESİ", "NURTEPE MAHALLESİ"
    ]
  },
  "Giresun": {
    "Keşap": ["GEÇİT KÖYÜ, TAMGERİŞ MEVKİİ"]
  },
  "Gümüşhane": {
    "Gümüşhane Merkez": ["YAĞLIDERE KÖYÜ, BULUT MEVKİİ"]
  },
  "Hatay": {
    "Altınözü": [
      "BOYNUYOĞUN MAHALLESİ", "YENİŞEHİR MAHALLESİ", "TOKAÇLI MAHALLESİ", "FATİKLİ MAHALLESİ", "SARILAR MAHALLESİ",
      "HACIPAŞA MAHALLESİ", "TÜRKMENMEZRAASI MAHALLESİ", "YENİHİSAR MAHALLESİ", "SARIBÜK MAHALLESİ", "SİVRİKAVAK MAHALLESİ",
      "TOKDEMİR MAHALLESİ", "KANSU MAHALLESİ", "AVUTTEPE MAHALLESİ"
    ],
    "Antakya": [
      "APAYDIN MAHALLESİ", "MEYDAN MAHALLESİ", "NARLICA MAHALLESİ", "ŞEYHALİ MAHALLESİ", "ORHANLI MAHALLESİ",
      "KOCAABDİ MAHALLESİ", "HACI ÖMER ALPAGOT MAHALLESİ", "BARBAROS MAHALLESİ", "HABİB-İ NECCAR MAHALLESİ", "AKÇAOVA MAHALLESİ",
      "HARAPARASI MAHALLESİ", "İPLİK PAZARI MAHALLESİ", "EMEK MAHALLESİ", "BİNİCİLER MAHALLESİ", "ŞEHİTLER MAHALLESİ",
      "AKHİSAR MAHALLESİ", "AKSARAY MAHALLESİ", "MELEKLİ MAHALLESİ", "YENİ CAMİİ MAHALLESİ", "ULUCAMİİ MAHALLESİ",
      "SOFULAR MAHALLESİ", "AYDINLIKEVLER MAHALLESİ", "DUTDİBİ MAHALLESİ", "MAŞUKLU MAHALLESİ", "CUMHURİYET MAHALLESİ",
      "ALTINÇAY MAHALLESİ", "AVSUYU MAHALLESİ", "BOZHÖYÜK MAHALLESİ", "BOHŞİN MAHALLESİ"
    ],
    "Belen": ["CUMHURİYET MAHALLESİ", "BAKRAS MAHALLESİ", "DEREBAHÇE MAHALLESİ", "MUHLİSALİ MAHALLESİ"],
    "İskenderun": ["MURADİYE MAHALLESİ", "ESENTEPE MAHALLESİ", "BARBAROS MAHALLESİ", "CUMHURİYET MAHALLESİ", "DUMLUPINAR MAHALLESİ"],
    "Kırıkhan": [
      "TORUN MAHALLESİ", "KURTULUŞ MAHALLESİ", "GÜNDÜZ MAHALLESİ", "ÇİLOĞLANHÜYÜĞÜ MAHALLESİ", "GÜLTEPE MAHALLESİ",
      "YENİ MAHALLESİ", "MENDERES MAHALLESİ", "ALSANCAK MAHALLESİ", "BARBAROS MAHALLESİ", "FATİH MAHALLESİ",
      "408 EVLER MAHALLESİ", "MURATPAŞA MAHALLESİ", "GAZİ MAHALLESİ", "ÇATALTEPE MAHALLESİ", "AYDINLI MAHALLESİ",
      "ALPARSLAN MAHALLESİ", "MAHMUTLU MAHALLESİ", "BAHÇELİEVLER MAHALLESİ", "GÜVENTAŞI MAHALLESİ", "CUMHURİYET MAHALLESİ"
    ],
    "Kumlu": ["HAMAM MAHALLESİ", "GÖKÇEOĞLU MAHALLESİ", "CUMHURİYET MAHALLESİ", "FEVZİ ÇAKMAK MAHALLESİ", "AKKUYU MAHALLESİ", "MUHARREM MAHALLESİ"],
    "Payas": ["YILDIRIM BEYAZIT MAHALLESİ"],
    "Reyhanlı": [
      "CUMHURİYET MAHALLESİ", "DAVUTPAŞA MAHALLESİ", "BÜKÜLMEZ MAHALLESİ", "KURTULUŞ MAHALLESİ", "BAĞLAR MAHALLESİ",
      "FİDANLIK MAHALLESİ", "GÜLTEPE MAHALLESİ", "BAHÇELİEVLER MAHALLESİ", "YENİŞEHİR MAHALLESİ", "PINARBAŞI MAHALLESİ",
      "YENİ MAHALLESİ", "CİLVEGÖZÜ MAHALLESİ", "MUSTAFA KEMAL MAHALLESİ", "BAYIR MAHALLESİ", "ESENTEPE MAHALLESİ",
      "UZUNKAVAK MAHALLESİ", "DEĞİRMENKAŞI MAHALLESİ", "YEŞİLOVA MAHALLESİ", "ADABUCAK MAHALLESİ", "TAYFURSÖKMEN MAHALLESİ",
      "CÜDEYDE MAHALLESİ", "AKYAYLA MAHALLESİ", "GÖKTEPE MAHALLESİ", "PAŞAHÜYÜK MAHALLESİ", "AHMETBEYLİ MAHALLESİ",
      "HARRAN MAHALLESİ", "GAZİMÜRSELTEPESİ MAHALLESİ", "ALAKUZU MAHALLESİ", "KARASÜLEYMANLI MAHALLESİ"
    ],
    "Yayladağı": ["KURTULUŞ MAHALLESİ", "TUTLUBAHÇE MAHALLESİ"]
  },
  "Iğdır": {
    "Aralık": ["EMİNCE KÖYÜ, TİGEM MEVKİİ"]
  },
  "Isparta": {
    "Isparta Merkez": ["BAHÇELİEVLER MAHALLESİ", "BAĞLAR MAHALLESİ", "PİRİMEHMET MAHALLESİ"],
    "Keçiborlu": ["AŞAĞI MAHALLESİ"]
  },
  "İstanbul": {
    "Avcılar": ["TÜM MAHALLELER"],
    "Bağcılar": ["TÜM MAHALLELER"],
    "Bahçelievler": ["TÜM MAHALLELER"],
    "Başakşehir": ["TÜM MAHALLELER"],
    "Esenler": ["TÜM MAHALLELER"],
    "Esenyurt": ["TÜM MAHALLELER"],
    "Fatih": ["TÜM MAHALLELER"],
    "Küçükçekmece": ["TÜM MAHALLELER"],
    "Sultangazi": ["TÜM MAHALLELER"],
    "Zeytinburnu": ["TÜM MAHALLELER"],
    "Beşiktaş": ["YILDIZ MAHALLESİ"],
    "Beylikdüzü": ["BEYLİKDÜZÜOSB MAHALLESİ"],
    "Beyoğlu": [
      "KOCATEPE MAHALLESİ", "ŞEHİT MUHTAR MAHALLESİ", "BÜLBÜL MAHALLESİ", "ÇUKUR MAHALLESİ", "KAMER HATUN MAHALLESİ",
      "KALYONCU KULLUĞU MAHALLESİ", "YENİŞEHİR MAHALLESİ", "KATİPMUSTAFA ÇELEBİ MAHALLESİ", "BOSTAN MAHALLESİ", "ASMALI MESCİT MAHALLESİ"
    ],
    "Sarıyer": ["MASLAK MAHALLESİ"],
    "Şile": ["MEŞRUTİYET MAHALLESİ"],
    "Şişli": ["İNÖNÜ MAHALLESİ", "ERGENEKON MAHALLESİ", "MECİDİYE MAHALLESİ", "CUMHURİYET MAHALLESİ"],
    "Tuzla": ["AYDINLI-KOSB MAHALLESİ"],
    "Ümraniye": ["DUDULLU OSB MAHALLESİ"]
  },
  "İzmir": {
    "Bornova": ["YUNUS EMRE MAHALLESİ", "IŞIKLAR MAHALLESİ", "ZAFER MAHALLESİ", "SERİNTEPE MAHALLESİ"],
    "Buca": ["SEYHAN MAHALLESİ"],
    "Karabağlar": ["AŞIK VEYSEL MAHALLESİ"],
    "Konak": [
      "TAN MAHALLESİ", "FAİK PAŞA MAHALLESİ", "YENİ MAHALLESİ", "MİRALİ MAHALLESİ", "ALİ REİS MAHALLESİ",
      "ETİLER MAHALLESİ", "SAKARYA MAHALLESİ", "ALTAY MAHALLESİ", "BOZKURT MAHALLESİ", "PAZARYERİ MAHALLESİ",
      "ALTINORDU MAHALLESİ", "UĞUR MAHALLESİ", "KUBİLAY MAHALLESİ", "SÜVARİ MAHALLESİ", "YEŞİLDERE MAHALLESİ",
      "KOCAKAPI MAHALLESİ", "AKARCALI MAHALLESİ", "MURAT MAHALLESİ", "KADİFEKALE MAHALLESİ"
    ],
    "Torbalı": ["19 MAYIS MAHALLESİ", "KARŞIYAKA MAHALLESİ"]
  },
  "Kahramanmaraş": {
    "Dulkadiroğlu": [
      "SİVRİCEHÜYÜK MAHALLESİ", "MENDERES MAHALLESİ", "TURAN MAHALLESİ", "SAKARYA MAHALLESİ", "İSA DİVANLI MAHALLESİ",
      "KURTULUŞ MAHALLESİ", "EKMEKÇİ MAHALLESİ", "FEVZİ PAŞA MAHALLESİ", "DURAKLI MAHALLESİ", "DİVANLI MAHALLESİ",
      "İSMET PAŞA MAHALLESİ", "KAYABAŞI MAHALLESİ", "SENEM AYŞE MAHALLESİ", "DULKADİROĞLU MAHALLESİ", "BAĞLARBAŞI MAHALLESİ",
      "GAZİ PAŞA MAHALLESİ", "YAVUZ SELİM MAHALLESİ", "NAMIK KEMAL MAHALLESİ", "ŞEYH ADİL MAHALLESİ"
    ],
    "Onikişubat": [
      "YUSUFLAR MAHALLESİ", "AKÇAKOYUNLU MAHALLESİ", "DUMLUPINAR MAHALLESİ", "ŞEHİT EVLİYA MAHALLESİ", "YÜRÜKSELİM MAHALLESİ",
      "MAĞRALI MAHALLESİ", "ERTUĞRUL GAZİ MAHALLESİ", "SERİNTEPE MAHALLESİ", "HACI BAYRAM VELİ MAHALLESİ", "HAYRULLAH MAHALLESİ",
      "BARBAROS MAHALLESİ", "KARACAOĞLAN MAHALLESİ", "MALİK EJDER MAHALLESİ"
    ]
  },
  "Karabük": {
    "Karabük Merkez": ["KILAVUZLAR MAHALLESİ", "100.YIL MAHALLESİ", "HÜRRİYET MAHALLESİ", "BAYIR MAHALLESİ"],
    "Safranbolu": ["KARIT KÖYÜ, KARIT MÜCAVİR MEVKİİ", "BOSTANBÜKÜ KÖYÜ, KARŞIYAKA MEVKİİ", "BOSTANBÜKÜ KÖYÜ, MERKEZ MEVKİİ"]
  },
  "Karaman": {
    "Karaman Merkez": ["ORGANİZE SANAYİİ BÖLGESİ MAHALLESİ"]
  },
  "Kastamonu": {
    "Devrekani": ["BINGILDAYIK KÖYÜ, ORUÇ MEVKİİ", "TEKKEKIZILLAR KÖYÜ, KURMALAR MEVKİİ", "BOZKOCA KÖYÜ, ÇAKALLAR MEVKİİ"],
    "Kastamonu Merkez": ["TOPÇUOĞLU MAHALLESİ", "CEBRAİL MAHALLESİ", "İSLAM KÖYÜ, SOFRANLAR MEZRASI", "ÖRENCİK KÖYÜ, İZBELİ MEZRASI"]
  },
  "Kayseri": {
    "Kocasinan": [
      "SAHABİYE MAHALLESİ", "HASAN ARPA MAHALLESİ", "ARGINCIK MAHALLESİ", "FEVZİ ÇAKMAK MAHALLESİ", "UĞUREVLER MAHALLESİ",
      "HACI SAKİ MAHALLESİ", "YAZIR MAHALLESİ"
    ],
    "Melikgazi": [
      "DANİŞMENTGAZİ MAHALLESİ", "OSMANLI MAHALLESİ", "CUMHURİYET MAHALLESİ", "SELÇUKLU MAHALLESİ",
      "AYDINLIKEVLER MAHALLESİ", "GÜLÜK MAHALLESİ", "KILIÇASLAN MAHALLESİ"
    ]
  },
  "Kırklareli": {
    "Lüleburgaz": ["SARIMSAKLI MAHALLESİ"]
  },
  "Kırşehir": {
    "Akçakent": ["YETİKLİ KÖYÜ, GÜNEŞLİ MEVKİİ"],
    "Kırşehir Merkez": ["SEYREKKÖY KÖYÜ"],
    "Mucur": ["KARACALI KÖYÜ"]
  },
  "Kilis": {
    "Elbeyli": [
      "BEŞİRİYE KÖYÜ", "YAĞIZKÖY KÖYÜ, AYNAFAR MEZRASI", "MERCANLI KÖYÜ", "YAĞIZKÖY KÖYÜ, DELHEMİ MEZRASI",
      "İNÖNÜ MAHALLESİ", "TAŞLIBAKAR KÖYÜ", "YALÇIN NANE MAHALLESİ", "HAVUZLUÇAM KÖYÜ", "AĞYÜZ MAHALLESİ"
    ],
    "Kilis Merkez": [
      "BÜYÜKKÜTAH MAHALLESİ", "TEKYE MAHALLESİ", "NURETTİN MAHALLESİ", "KETENCİLER MAHALLESİ", "CANPOLAT PAŞA MAHALLESİ",
      "TIRIKLI MAHALLESİ", "ALTINÜZÜM MAHALLESİ", "YEDİ ARALIK MAHALLESİ", "ŞIHLAR MAHALLESİ", "DEVECİLER MAHALLESİ",
      "İNNAPLI KÜTAH MAHALLESİ", "ŞEHİTLER MAHALLESİ", "İSLAMBEY MAHALLESİ", "YENİ MAHALLESİ", "HİNDİOĞLU MAHALLESİ",
      "TABAKHANE MAHALLESİ", "MEŞETLİK MAHALLESİ", "ASLAN MAHALLESİ", "ŞIH ABDULLAH MAHALLESİ", "CUMHURİYET MAHALLESİ",
      "YAVUZ SULTAN SELİM MAHALLESİ", "HAKVERDİ MAHALLESİ", "MIHALİ MAHALLESİ", "ŞEHİT SAKIP MAHALLESİ", "ZEYTİNLİ MAHALLESİ",
      "TOSYALI MAHALLESİ", "OSMAN GAZİ MAHALLESİ", "ABDİOYMAĞI MAHALLESİ", "NACAROĞLU MAHALLESİ", "HASAN KAMİL DEMİRBAŞ MAHALLESİ",
      "MERCİDABIK MAHALLESİ", "HACI GÜMÜŞ MAHALLESİ", "MARAŞAL FEVZİ ÇAKMAK MAHALLESİ", "BÖLÜK MAHALLESİ", "HÜRRİYET MAHALLESİ",
      "ÇAYLAK MAHALLESİ", "AŞIT MAHALLESİ", "HACI İLYAS MAHALLESİ", "NAMIK KEMAL MAHALLESİ", "SARAÇ MEHMET ÇAVUŞ MAHALLESİ",
      "NEDİM ÖKMEN MAHALLESİ", "ŞIH AHMET MAHALLESİ", "MULLAHAMİT MAHALLESİ", "POLAT PAŞA MAHALLESİ", "OKÇULAR MAHALLESİ",
      "KARAALİ MAHALLESİ", "MÜSLÜMANBEY MAHALLESİ", "AKPINAR MAHALLESİ", "KARTALBEY MAHALLESİ", "İSMET PAŞA MAHALLESİ",
      "VAİZ MAHALLESİ", "EKREM ÇETİN MAHALLESİ", "KAZIM KARABEKİR MAHALLESİ", "GAZİLER MAHALLESİ", "YAŞAR AKTÜRK MAHALLESİ",
      "DURUCA KÖYÜ, AKDİLEK MEZRASI", "NAMIK ÜNLER PAŞA MAHALLESİ", "DEMİRCİLER MAHALLESİ", "BARIŞ MAHALLESİ",
      "KANUNİ SULTAN SÜLEYMAN MAHALLESİ", "ATATÜRK MAHALLESİ", "ŞIH MEHMET MAHALLESİ", "ŞÖRHABİL MAHALLESİ",
      "FATİH SULTAN MEHMET MAHALLESİ", "MUALLİM RIFAT BİLGE MAHALLESİ", "EBULÜLE MAHALLESİ", "BİLALİ HABEŞ MAHALLESİ",
      "DOĞAN GÜREŞ PAŞA MAHALLESİ", "ÖNCÜ PINAR MAHALLESİ", "MÜCAHİTLER MAHALLESİ", "MEHMET ABDİ BULUT MAHALLESİ",
      "OYLUM MAHALLESİ", "AKÇABAĞLAR KÖYÜ", "ALBAY İBRAHİM KARAOĞLANOĞLU MAHALLESİ"
    ]
  },
  "Konya": {
    "Ereğli / Konya": ["SELÇUKLU MAHALLESİ"],
    "Kadınhanı": ["KÜÇÜKKUYU MAHALLESİ"],
    "Karapınar": ["SELİMİYE MAHALLESİ"],
    "Karatay": ["ŞEMSİTEBRİZİ MAHALLESİ", "AZİZİYE MAHALLESİ", "SULTAN MESUD MAHALLESİ", "AKÇEŞME MAHALLESİ", "NAKİPOĞLU MAHALLESİ"],
    "Meram": ["SAHİBATA MAHALLESİ", "ÇAYBAŞI MAHALLESİ", "PİREBİ MAHALLESİ", "UZUNHARMANLAR MAHALLESİ", "AYDOĞDU MAHALLESİ"],
    "Selçuklu": ["BÜYÜKKAYACIKOSB MAHALLESİ", "İHSANİYE MAHALLESİ", "DOKUZ MAHALLESİ", "FERHUNİYE MAHALLESİ", "HOROZLUHANOSB MAHALLESİ"]
  },
  "Kütahya": {
    "Kütahya Merkez": ["KİRAZPINAR MAHALLESİ", "SARAY MAHALLESİ"]
  },
  "Malatya": {
    "Battalgazi": [
      "YENİHAMAM MAHALLESİ", "DABAKHANE MAHALLESİ", "AKPINAR MAHALLESİ", "KAVAKLIBAĞ MAHALLESİ", "BEYLERBAŞI MAHALLESİ",
      "B.HÜSEYİNBEY MAHALLESİ", "SARAY MAHALLESİ", "İZZETİYE MAHALLESİ", "TAŞTEPE MAHALLESİ", "HALFETTİN MAHALLESİ",
      "FERHADİYE MAHALLESİ", "İSMETİYE MAHALLESİ", "İSTİKLAL MAHALLESİ", "HAMİDİYE MAHALLESİ", "ŞEHİTFEVZİ MAHALLESİ"
    ],
    "Yeşilyurt / Malatya": ["FATİH MAHALLESİ"]
  },
  "Manisa": {
    "Soma": ["TÜRKPİYALA MAHALLESİ"]
  },
  "Mardin": {
    "Artuklu": [
      "KARADEMİR MAHALLESİ", "ŞEHİDİYE MAHALLESİ", "DİBEKTAŞ MAHALLESİ", "ULUCAMİ MAHALLESİ", "TEKER MAHALLESİ",
      "LATİFİYE MAHALLESİ", "TOZAN MAHALLESİ", "NECMETTİN MAHALLESİ", "SAVURKAPI MAHALLESİ", "DİYARBAKIR KAPI MAHALLESİ",
      "ALAKUŞ MAHALLESİ", "EMİNETTİN MAHALLESİ", "YENİKAPI MAHALLESİ", "ENSAR MAHALLESİ", "YENİCE MAHALLESİ"
    ],
    "Derik": ["KUYULU MAHALLESİ", "DOĞANCI MAHALLESİ", "KÖSEVELİ MAHALLESİ", "ORTACA MAHALLESİ", "BAŞARAN MAHALLESİ", "KANATLI MAHALLESİ"],
    "Kızıltepe": [
      "ÜLKER MAHALLESİ", "GÜNGÖREN MAHALLESİ", "KIRKKUYU MAHALLESİ", "DORA MAHALLESİ", "DEMİRCİ MAHALLESİ",
      "YAYIKLI MAHALLESİ", "TIRAŞLI MAHALLESİ", "GÖZLÜCE MAHALLESİ", "YEŞİLKÖY MAHALLESİ", "TATLICA MAHALLESİ",
      "ESENLİ MAHALLESİ", "YONCALI MAHALLESİ", "SEVİMLİ MAHALLESİ", "YUMRUTAŞ MAHALLESİ", "BELLİ MAHALLESİ",
      "ÇİTLİBAĞ MAHALLESİ", "KATARLI MAHALLESİ", "HACIYUSUF MAHALLESİ", "ÇAMLICA MAHALLESİ", "ULAŞLI MAHALLESİ",
      "ATAKÖY MAHALLESİ", "TANRIVERDİ MAHALLESİ", "TİMURÇİFTLİĞİ MAHALLESİ", "ALTINTOPRAK MAHALLESİ", "KALAYCIK MAHALLESİ",
      "BÜYÜKAYRIK MAHALLESİ", "YURTÖZÜ MAHALLESİ", "IŞIKÖREN MAHALLESİ", "TARLABAŞI MAHALLESİ", "AKKOÇ MAHALLESİ",
      "YUMURCAK MAHALLESİ", "İKİZLER MAHALLESİ", "ORTAKÖY MAHALLESİ", "CANTAŞI MAHALLESİ"
    ],
    "Midyat": ["IŞIKLAR MAHALLESİ"],
    "Nusaybin": ["PAZAR MAHALLESİ", "AKÇATARLA MAHALLESİ", "DİRİM MAHALLESİ"]
  },
  "Mersin": {
    "Akdeniz": [
      "ADANALIOĞLU LİMONLU MAHALLESİ", "SİTELER MAHALLESİ", "KÜLTÜR MAHALLESİ", "CAMİ ŞERİF MAHALLESİ", "CUMHURİYET MAHALLESİ",
      "ÇANKAYA MAHALLESİ", "MESUDİYE MAHALLESİ", "ABDULLAH ŞAHUTOĞLU MAHALLESİ", "HAMİDİYE MAHALLESİ", "KİREMİTHANE MAHALLESİ",
      "ÜÇOCAK MAHALLESİ", "HÜRRİYET MAHALLESİ", "MAHMUDİYE MAHALLESİ", "BARIŞ MAHALLESİ", "KAZANLI MAHALLESİ",
      "HAL MAHALLESİ", "AKDENİZ MAHALLESİ", "TURGUTREİS MAHALLESİ", "YENİ MAHALLESİ", "MÜFİDE İLHAN MAHALLESİ",
      "BAHÇE MAHALLESİ", "ÖZGÜRLÜK MAHALLESİ", "MİTHATPAŞA MAHALLESİ", "GÜNDOĞDU MAHALLESİ", "NUSRATİYE MAHALLESİ",
      "YEŞİLÇİMEN MAHALLESİ", "ÇAY MAHALLESİ"
    ],
    "Erdemli": ["KIZKALESİ MAHALLESİ"],
    "Gülnar": ["YANIŞLI MAHALLESİ"],
    "Mezitli": ["İSTİKLAL MAHALLESİ", "FATİH MAHALLESİ", "SEYMENLİ MAHALLESİ", "VİRANŞEHİR MAHALLESİ", "YENİ MAHALLESİ"],
    "Silifke": ["ARKUM MAHALLESİ", "SAY MAHALLESİ", "SÖKÜN MAHALLESİ", "TOSMURLU OSB MAHALLESİ", "KURTULUŞ MAHALLESİ", "PAZARKAŞI MAHALLESİ"],
    "Tarsus": [
      "KONAKLAR MAHALLESİ", "ÇATALCA MAHALLESİ", "YUNUS EMRE MAHALLESİ", "EGEMEN MAHALLESİ", "KULAK MAHALLESİ",
      "BAHŞİŞ MAHALLESİ", "YEŞİLTEPE MAHALLESİ", "ATALAR MAHALLESİ", "ÇÖPLÜ MAHALLESİ", "82EVLER MAHALLESİ",
      "KELAHMET MAHALLESİ", "BARBAROS MAHALLESİ", "KARGILI MAHALLESİ", "AKARSU MAHALLESİ", "BAHARLI MAHALLESİ",
      "ŞEHİTKERİM MAHALLESİ", "GİRNE MAHALLESİ", "BAHÇE MAHALLESİ"
    ],
    "Toroslar": ["TURUNÇLU MAHALLESİ", "ALSANCAK MAHALLESİ", "DEMİRTAŞ MAHALLESİ"],
    "Yenişehir / Mersin": ["DUMLUPINAR MAHALLESİ", "PALMİYE MAHALLESİ"]
  },
  "Muğla": {
    "Fethiye": ["ÖLÜDENİZ MAHALLESİ"],
    "Seydikemer": ["KUMLUOVA MAHALLESİ"]
  },
  "Muş": {
    "Muş Merkez": ["AŞAĞISIZMA KÖYÜ, MEVKİİ"]
  },
  "Nevşehir": {
    "Derinkuyu": ["BAŞ MAHALLESİ", "BAYRAMLI MAHALLESİ", "CUMHURİYET MAHALLESİ", "FATİH MAHALLESİ"],
    "Nevşehir Merkez": [
      "YENİ MAHALLESİ", "KAPUCUBAŞI MAHALLESİ", "KARASOKU MAHALLESİ", "CAMİCEDİT MAHALLESİ", "İBRAHİMPAŞA MAHALLESİ",
      "HACIRÜŞTÜ MAHALLESİ", "HERİKLİ MAHALLESİ", "RAŞİTBEY MAHALLESYİ", "350 EVLER MAHALLESİ"
    ],
    "Ürgüp": ["BAŞDERE KÖYÜ, SULTANIM MEVKİİ", "BAŞDERE KÖYÜ, EYÜPLÜ MEVKİİ"]
  },
  "Niğde": {
    "Bor": ["ORGANİZE SANAYİ BÖLGESİ MAHALLESİ", "ORTA MAHALLESİ"],
    "Niğde Merkez": ["ALAADDİN MAHALLESİ", "AHİPAŞA MAHALLESİ", "SIRALİ MAHALLESİ", "KALE MAHALLESİ", "BALHASAN MAHALLESİ"],
    "Ulukışla": ["HACIBEKİRLİ KÖYÜ", "ALTAY KÖYÜ, KÜME2 MEVKİİ", "PORSUK KÖYÜ, KÜME1 MEVKİİ"]
  },
  "Osmaniye": {
    "Düziçi": ["GÖKÇAYIR KÖYÜ, ARPAÇUKURU MEVKİİ"],
    "Kadirli": ["KİREMİTLİ KÖYÜ, HOCALAR MEVKİİ", "TOPRAKTEPE KÖYÜ, TIBILILAR MEVKİİ", "SAVRUN MAHALLESİ"],
    "Osmaniye Merkez": [
      "CEVDETİYE BELDESİ, YEŞİLTEPE MAHALLESİ", "DERVİŞLİ KÖYÜ, İBİŞ AĞALAR E-24 KARAYOLU ÜZERİ MEVKİİ",
      "CUMHURİYET MAHALLESİ", "İSTİKLAL MAHALLESİ"
    ]
  },
  "Rize": {
    "Çayeli": ["ABDULLAHHOCA KÖYÜ, OKUMUŞ ÇAY MEVKİİ"]
  },
  "Sakarya": {
    "Adapazarı": ["TIĞCILAR MAHALLESİ"],
    "Sapanca": ["İLMİYE MAHALLESİ", "KURTKÖY DİBEKTAŞ MAHALLESİ"]
  },
  "Samsun": {
    "Atakum": ["DENİZEVLERİ MAHALLESİ"],
    "Canik": ["SOĞUKSU MAHALLESİ"],
    "İlkadım": ["19 MAYIS MAHALLESİ", "HÜRRİYET MAHALLESİ", "ZAFER MAHALLESİ"]
  },
  "Sinop": {
    "Ayancık": ["ÜNLÜCE KÖYÜ, YALI MEVKİİ"],
    "Boyabat": ["OSMANKÖY KÖYÜ, OSMANKÖY KÜMEEVLER MÜCAVİR MEVKİİ"]
  },
  "Sivas": {
    "Sivas Merkez": ["AHMETTURANGAZİ OSB MAHALLESİ"],
    "Şarkışla": ["ALIKÖREN KÖYÜ"],
    "Ulaş": ["DEMİRCİLİK KÖYÜ, AŞAĞI DEMİRCİLİK MEZRASI"],
    "Zara": ["AVŞAR KÖYÜ, BUĞDAYLI (ŞAHİN ÇAVUŞLAR) MEZRASI", "AŞAĞIÇAMURCU KÖYÜ, GİLGİL MEZRASI"]
  },
  "Şanlıurfa": {
    "Akçakale": [
      "İKİZCE MAHALLESİ", "ŞANLI MAHALLESİ", "ADNAN MENDERES MAHALLESİ", "YAĞMURALAN MAHALLESİ", "TATLICA MAHALLESİ",
      "GÜLVEREN MAHALLESİ", "KIRMITLI MAHALLESİ", "GÜVENÇ MAHALLESİ", "İNCEDERE MAHALLESİ", "YENİŞEHİR MAHALLESİ",
      "YENİ MAHALLESİ", "CEYLANLI MAHALLESİ", "FEVZİ ÇAKMAK MAHALLESİ", "GÜNDAŞ MAHALLESİ", "ÇAKIRLAR MAHALLESİ",
      "EDEBEY MAHALLESİ", "YALINLI MAHALLESİ", "ŞAHİNLER MAHALLESİ", "SÜLEYMANŞAH MAHALLESİ", "BUKET MAHALLESİ",
      "TURGUT ÖZAL MAHALLESİ", "HÜRRİYET MAHALLESİ", "ALATLAR MAHALLESİ", "ATATÜRK MAHALLESİ", "OKAYLAR MAHALLESİ",
      "BÜYÜCEK MAHALLESİ", "AŞAĞIDEREN MAHALLESİ", "FATİH SULTAN MEHMET MAHALLESİ", "ERECEK MAHALLESİ", "AKÇAKÖY MAHALLESİ",
      "BİLECE MAHALLESİ", "GÜNEREN MAHALLESİ", "SALİHLER MAHALLESİ", "KURUDERE MAHALLESİ", "ÖNCÜL MAHALLESİ",
      "AYDINLI MAHALLESİ", "ÇOKALAN MAHALLESİ", "YUKARI ÇUKURCA MAHALLESİ", "KÖSEÖREN MAHALLESİ", "ZORLU MAHALLESİ",
      "TOPÇU MAHALLESİ"
    ],
    "Birecik": ["MERKEZ MAHALLESİ", "SANCAK MAHALLESİ", "HOCA ŞERİF MAHALLESİ"],
    "Bozova": ["KONUKSEVER MAHALLESİ", "KINDIRALİ MAHALLESİ", "ÖZGÖREN MAHALLESİ"],
    "Ceylanpınar": [
      "MEVLANA MAHALLESİ", "AŞAĞIDORUKLU MAHALLESİ", "YUKARITAŞLIDERE MAHALLESİ", "YENİŞEHİR MAHALLESİ",
      "ULUCAMİ MAHALLESİ", "ADNAN MENDERES MAHALLESİ"
    ],
    "Eyyübiye": [
      "PINARBAŞI MAHALLESİ", "KARAKOYUNLU MAHALLESİ", "TÜRKMEYDANI MAHALLESİ", "EYÜPKENT MAHALLESİ", "KURTULUŞ MAHALLESİ",
      "KADIOĞLU MAHALLESİ", "YUSUFPAŞA MAHALLESİ", "BEYKAPUSU MAHALLESİ", "HAKİMDEDE MAHALLESİ", "AKÇAMESCİT MAHALLESİ",
      "YENİ MAHALLESİ", "CAMİKEBİR MAHALLESİ", "BIÇAKÇI MAHALLESİ", "ASYA MAHALLESİ", "YAKUBİYE MAHALLESİ",
      "HAYATİ HARRANİ MAHALLESİ", "RUHA MAHALLESİ", "BAKIŞLAR MAHALLESİ", "KENDİRCİ MAHALLESİ", "ZEYNEPKÖY MAHALLESİ",
      "ÇALIŞKANLAR MAHALLESİ", "DİREKLİ MAHALLESİ", "GÜMÜŞKUŞAK MAHALLESİ", "AÇMALI MAHALLESİ", "HALEPLİBAHÇE MAHALLESİ",
      "AKŞEMSETTİN MAHALLESİ", "TEPE MAHALLESİ", "KUBACIK MAHALLESİ", "AKMEŞHET MAHALLESİ", "GÖL MAHALLESİ", "AKABE MAHALLESİ"
    ],
    "Halfeti": ["KARAOTLAK MAHALLESİ"],
    "Haliliye": [
      "ATATÜRK MAHALLESİ", "MİMAR SİNAN MAHALLESİ", "BAHÇELİEVLER MAHALLESİ", "ŞEHİTLIK MAHALLESİ", "YEŞİLYURT MAHALLESİ",
      "KAMBERİYE MAHALLESİ", "HIZMALI MAHALLESİ", "CENGİZ TOPEL MAHALLESİ", "ORTAÖREN MAHALLESİ", "ŞAİR ŞEVKET MAHALLESİ",
      "NOKTA MAHALLESİ", "SULTAN FATİH MAHALLESİ", "BAĞLARBAŞI MAHALLESİ", "PERŞEMBE MAHALLESİ", "BAMYASUYU MAHALLESİ",
      "ŞAİR NABİ MAHALLESİ", "KÖSECİK MAHALLESİ", "SANCAKTAR MAHALLESİ", "DAĞYANI MAHALLESİ", "SÜLEYMANİYE MAHALLESİ",
      "YAVUZ SELİM MAHALLESİ", "İPEKYOL MAHALLESİ", "DERİNKUYU MAHALLESİ", "YENİŞEHİR MAHALLESİ", "ASRİ MAHALLESİ"
    ],
    "Harran": [
      "KÖKENLİ MAHALLESİ", "TOYTEPE MAHALLESİ", "YAYVANDORUK MAHALLESİ", "SAİDE MAHALLESİ", "SOYLU MAHALLESİ",
      "ŞEYH HAYATİ HARRANİ MAHALLESİ", "HZ. YAKUP MAHALLESİ", "AVLAK MAHALLESİ", "CUMHURİYET MAHALLESİ", "BOZYAZI MAHALLESİ",
      "ZEYTİNDALI MAHALLESİ", "BELLİTAŞ MAHALLESİ", "ALACALI MAHALLESİ", "AYDINCIK MAHALLESİ", "KÜÇÜKYILDIZ MAHALLESİ",
      "ARIN MAHALLESİ", "HAZRETİ İMAMBAKIR MAHALLESİ", "MEYDANKAPI MAHALLESİ", "ÖZTAŞ MAHALLESİ", "ÇATALHURMA MAHALLESİ",
      "İBNİ TEYMİYE MAHALLESİ", "ŞÜKÜRALİ MAHALLESİ", "ÇİÇEK MAHALLESİ", "KIRMITLI MAHALLESİ", "SÜLEYMAN DEMİREL MAHALLESİ",
      "KOYUNLUCA MAHALLESİ"
    ],
    "Hilvan": ["USTAHASAN MAHALLESİ"],
    "Karaköprü": ["BÜYÜKÖRDEK MAHALLESİ", "YIĞINAK MAHALLESİ", "AKÇAHİSAR MAHALLESİ"],
    "Siverek": ["KALEMLİ MAHALLESİ", "KEŞ MAHALLESİ", "AYRANCI MAHALLESİ"],
    "Suruç": [
      "KÜÇÜKSERGEN MAHALLESİ", "OYMAKLI MAHALLESİ", "DİKİLİ MAHALLESİ", "TOPÇULAR MAHALLESİ", "HÜRRİYET MAHALLESİ",
      "YILDIRIM MAHALLESİ", "CUMHURİYET MAHALLESİ"
    ],
    "Viranşehir": [
      "ŞEHİT MAHALLESİ", "SÖZERİ MAHALLESİ", "KOLAĞASI MAHALLESİ", "ÖVÜNCÜK MAHALLESİ", "UĞURLU MAHALLESİ",
      "GÜRPINAR MAHALLESİ", "ÇİFTÇİLER MAHALLESİ", "OĞLAKÇI MAHALLESİ", "ULAKLI MAHALLESİ", "YILDIZ MAHALLESİ",
      "KALE MAHALLESİ", "ÜÇGÜL MAHALLESİ", "YÜCELER MAHALLESİ", "TEKKE MAHALLESİ", "BURÇ MAHALLESİ",
      "EŞKİN MAHALLESİ", "KAVURGA MAHALLESİ", "GÖKTEPE MAHALLESİ", "ŞARKPINAR MAHALLESİ", "AYAKLI MAHALLESİ"
    ]
  },
  "Tokat": {
    "Yeşilyurt / Tokat": ["TÜRKMENLER MAHALLESİ"]
  },
  "Trabzon": {
    "Ortahisar": ["PAZARKAPI MAHALLESİ"]
  },
  "Uşak": {
    "Eşme": ["İSTASYON MAHALLESİ"],
    "Uşak Merkez": ["MENDE KÖYÜ, KAŞBELEN MÜCAVİR MEVKİİ", "GÖĞEM KÖYÜ, GÖL MEVKİİ", "KÖME MAHALLESİ", "KARMA OSB MAHALLESİ", "ÖZDEMİR MAHALLESİ"]
  },
  "Yalova": {
    "Çınarcık": ["ÇAMLIK MAHALLESİ", "TAŞLİMAN MAHALLESİ", "HARMANLAR MAHALLESİ"],
    "Yalova Merkez": ["SUGÖREN KÖYÜ, SUGÖREN MÜCAVİR MEVKİİ", "BAHÇELİEVLER MAHALLESİ", "ADNAN MENDERES MAHALLESİ", "KAZIM KARABEKİR MAHALLESİ"]
  },
  "Yozgat": {
    "Yerköy": ["ARSLANHACILI KÖYÜ, YAYLAEVLERİ YAYLA EVLERİ", "SALİHLİ KÖYÜ"],
    "Yozgat Merkez": ["DAYILI KÖYÜ, ARAPLIÇİFTLİĞİ MEVKİİ", "KIRIM KÖYÜ, MOLLAHASAN MEVKİİ"]
  }
};