
export type CountryGroup = 'A' | 'B' | 'C' | 'D' | 'E';

export interface CountryRule {
  name: string;
  group: CountryGroup;
  visaDurationMonths: number; // Legal stay duration in months
  isVisaFeeExempt: boolean; // "Tek Giriş Vize Harcından Muaf" status
}

export const CONSTANTS_2025 = {
  VISA_FEE: 7882.70,
  CARD_FEE: 810.00,
  // Rates per group [First Month, Subsequent Months]
  RATES: {
    'A': { first: 50, month: 10 },
    'B': { first: 28, month: 7 },
    'C': { first: 18, month: 5 },
    'D': { first: 14, month: 3 },
    'E': { first: 10, month: 1 },
  }
};

// Complete list derived from PDF OCR data and "Tek Giriş Vize Harcından Muaf Ülkeler" list
export const COUNTRY_RULES: CountryRule[] = [
  // --- GROUP A ---
  { name: "Afganistan", group: 'A', visaDurationMonths: 1, isVisaFeeExempt: false },
  { name: "Almanya", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "ABD", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Andora", group: 'A', visaDurationMonths: 1, isVisaFeeExempt: false },
  { name: "Angola", group: 'A', visaDurationMonths: 1, isVisaFeeExempt: false },
  { name: "Antigua-Barbuda", group: 'A', visaDurationMonths: 1, isVisaFeeExempt: false },
  { name: "Arjantin", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Avustralya", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Avusturya", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Azerbaycan", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: true },
  { name: "Bahama", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Bahreyn", group: 'A', visaDurationMonths: 1, isVisaFeeExempt: false },
  { name: "Bangladeş", group: 'A', visaDurationMonths: 1, isVisaFeeExempt: false },
  { name: "Barbados", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Belize", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Benin", group: 'A', visaDurationMonths: 1, isVisaFeeExempt: false },
  { name: "Bhutan", group: 'A', visaDurationMonths: 1, isVisaFeeExempt: false },
  { name: "Birleşik Arap Emirlikleri", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Bolivya", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: true },
  { name: "Bosna Hersek", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: true },
  { name: "Botsvana", group: 'A', visaDurationMonths: 1, isVisaFeeExempt: false },
  { name: "Brezilya", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Brunei", group: 'A', visaDurationMonths: 1, isVisaFeeExempt: false },
  { name: "Bulgaristan", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Burkina Faso", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Burundi", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Cape Verde", group: 'A', visaDurationMonths: 1, isVisaFeeExempt: false },
  { name: "Cibuti", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Çad", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Çekya", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: true },
  { name: "Çin", group: 'A', visaDurationMonths: 1, isVisaFeeExempt: false },
  { name: "Danimarka", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Doğu Timor", group: 'A', visaDurationMonths: 1, isVisaFeeExempt: false },
  { name: "Dominik", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Dominika", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Ekvator", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Ekvator Ginesi", group: 'A', visaDurationMonths: 1, isVisaFeeExempt: false },
  { name: "El Salvador", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Endonezya", group: 'A', visaDurationMonths: 1, isVisaFeeExempt: false },
  { name: "Eritre", group: 'A', visaDurationMonths: 1, isVisaFeeExempt: false },
  { name: "Ermenistan", group: 'A', visaDurationMonths: 1, isVisaFeeExempt: true },
  { name: "Estonya", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Fas", group: 'E', visaDurationMonths: 3, isVisaFeeExempt: false }, 
  { name: "Fildişi Sahili", group: 'E', visaDurationMonths: 1, isVisaFeeExempt: false }, 
  { name: "Filistin", group: 'A', visaDurationMonths: 1, isVisaFeeExempt: false },
  { name: "Finlandiya", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Fransa", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Gabon", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Gambiya", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Gana", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Gine", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Gine-Bissau", group: 'A', visaDurationMonths: 1, isVisaFeeExempt: false },
  { name: "Grenada", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Guatemala", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Guyana", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Güney Afrika", group: 'A', visaDurationMonths: 1, isVisaFeeExempt: true },
  { name: "Güney Kıbrıs Rum Kesimi", group: 'A', visaDurationMonths: 1, isVisaFeeExempt: true },
  { name: "Gürcistan", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Haiti", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Hırvatistan", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: true },
  { name: "Hindistan", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Hollanda", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Honduras", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "İngiltere", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "İran", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: true },
  { name: "İrlanda", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "İsveç", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "İsviçre", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "İtalya", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "İzlanda", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Jamaika", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Kamerun", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Kanada", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Katar", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Kazakistan", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: true },
  { name: "Kenya", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Kırgızistan", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Kiribati", group: 'A', visaDurationMonths: 1, isVisaFeeExempt: false },
  { name: "Kolombiya", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Komorlar Birliği", group: 'A', visaDurationMonths: 1, isVisaFeeExempt: false },
  { name: "Kongo", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Kosta Rika", group: 'A', visaDurationMonths: 1, isVisaFeeExempt: false },
  { name: "Kuzey Kıbrıs (KKTC)", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: true },
  { name: "Kuzey Kore", group: 'A', visaDurationMonths: 1, isVisaFeeExempt: false },
  { name: "Küba", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Laos", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Lesotho", group: 'A', visaDurationMonths: 1, isVisaFeeExempt: false },
  { name: "Letonya", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Liberya", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Libya", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Lihtenştayn", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Litvanya", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Lübnan", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Macaristan", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Madagaskar", group: 'A', visaDurationMonths: 1, isVisaFeeExempt: false },
  { name: "Malavi", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Maldivler", group: 'A', visaDurationMonths: 1, isVisaFeeExempt: false },
  { name: "Malezya", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Mali", group: 'B', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Marshall Adaları", group: 'A', visaDurationMonths: 1, isVisaFeeExempt: false },
  { name: "Mauritius", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Meksika", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Mısır", group: 'E', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Moğolistan", group: 'A', visaDurationMonths: 1, isVisaFeeExempt: false },
  { name: "Moldova", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Monako", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Moritanya", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Mozambik", group: 'A', visaDurationMonths: 1, isVisaFeeExempt: false },
  { name: "Myanmar", group: 'A', visaDurationMonths: 1, isVisaFeeExempt: false },
  { name: "Namibya", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Nauru", group: 'A', visaDurationMonths: 1, isVisaFeeExempt: false },
  { name: "Nijer", group: 'A', visaDurationMonths: 1, isVisaFeeExempt: false },
  { name: "Nijerya", group: 'A', visaDurationMonths: 1, isVisaFeeExempt: false },
  { name: "Nikaragua", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Norveç", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Orta Afrika Cum.", group: 'A', visaDurationMonths: 1, isVisaFeeExempt: false },
  { name: "Özbekistan", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Pakistan", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Palau", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Panama", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Papua Yeni Gine", group: 'A', visaDurationMonths: 1, isVisaFeeExempt: false },
  { name: "Paraguay", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Peru", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Polonya", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Portekiz", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Romanya", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Ruanda", group: 'A', visaDurationMonths: 1, isVisaFeeExempt: false },
  { name: "Samoa", group: 'A', visaDurationMonths: 1, isVisaFeeExempt: false },
  { name: "San Marino", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Sao Tome", group: 'A', visaDurationMonths: 1, isVisaFeeExempt: false },
  { name: "Senegal", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Seyşeller", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Sierra Leone", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Slovakya", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Slovenya", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Solomon Adaları", group: 'A', visaDurationMonths: 1, isVisaFeeExempt: false },
  { name: "Somali", group: 'A', visaDurationMonths: 1, isVisaFeeExempt: false },
  { name: "St. Kitts", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "St. Lucia", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "St. Vincent", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Sudan", group: 'A', visaDurationMonths: 1, isVisaFeeExempt: false },
  { name: "Surinam", group: 'A', visaDurationMonths: 1, isVisaFeeExempt: false },
  { name: "Suudi Arabistan", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Svaziland", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Şili", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Tanzanya", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Tayland", group: 'A', visaDurationMonths: 1, isVisaFeeExempt: false },
  { name: "Togo", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Trinidad-Tobago", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Tunus", group: 'E', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Uganda", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Ukrayna", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Uruguay", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Vanuatu", group: 'A', visaDurationMonths: 1, isVisaFeeExempt: false },
  { name: "Vatikan", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Venezuela", group: 'A', visaDurationMonths: 1, isVisaFeeExempt: false },
  { name: "Vietnam", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Yemen", group: 'A', visaDurationMonths: 1, isVisaFeeExempt: false },
  { name: "Yeni Zelanda", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Yunanistan", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Zambiya", group: 'A', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Zimbabve", group: 'A', visaDurationMonths: 0, isVisaFeeExempt: false },

  // --- GROUP B ---
  { name: "Arnavutluk", group: 'B', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Filipinler", group: 'B', visaDurationMonths: 1, isVisaFeeExempt: false },
  { name: "İsrail", group: 'B', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Japonya", group: 'B', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Kamboçya", group: 'B', visaDurationMonths: 1, isVisaFeeExempt: false },
  { name: "Makedonya", group: 'B', visaDurationMonths: 3, isVisaFeeExempt: true },
  { name: "Tacikistan", group: 'B', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Umman", group: 'B', visaDurationMonths: 3, isVisaFeeExempt: false },

  // --- GROUP C ---
  { name: "Belçika", group: 'C', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Belarus", group: 'C', visaDurationMonths: 1, isVisaFeeExempt: false },
  { name: "Cezayir", group: 'C', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "İspanya", group: 'C', visaDurationMonths: 1, isVisaFeeExempt: false },
  { name: "Kuveyt", group: 'C', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Lüksemburg", group: 'C', visaDurationMonths: 3, isVisaFeeExempt: true },
  { name: "Malta", group: 'C', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Singapur", group: 'C', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Tayvan", group: 'C', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Ürdün", group: 'C', visaDurationMonths: 3, isVisaFeeExempt: false },

  // --- GROUP D ---
  { name: "Etiyopya", group: 'D', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Güney Kore", group: 'D', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Hong Kong", group: 'D', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Mikronezya", group: 'D', visaDurationMonths: 1, isVisaFeeExempt: false },
  { name: "Rusya", group: 'D', visaDurationMonths: 2, isVisaFeeExempt: false },

  // --- GROUP E ---
  { name: "Irak", group: 'E', visaDurationMonths: 1, isVisaFeeExempt: true },
  { name: "Karadağ", group: 'E', visaDurationMonths: 3, isVisaFeeExempt: false },
  { name: "Türkmenistan", group: 'E', visaDurationMonths: 1, isVisaFeeExempt: false }
];
